JNG-3391 Add parallel configuration
BlackBeltTechnology/flutter-maven-plugin pull request #2
Opened 2021-12-17 22:37 UTC by robertcsakany

2021-12-20 12:42 UTC, noherczeg requested changes

2021-12-20 12:42 UTC, noherczeg commented on README.adoc
> +<3> Parallel build enabled in maven.
<6>

2021-12-20 12:49 UTC, noherczeg approved these changes

2021-12-21 11:03 UTC, fruska approved these changes

2021-12-21 11:03 UTC, fruska commented on README.adoc
> +Maven supports parallel build with `-T` parameter. The plugin supports parallel build with limitations. When several flutter project is
... when several flutter projects are ...

2021-12-21 11:03 UTC, fruska commented on README.adoc
> +Maven supports parallel build with `-T` parameter. The plugin supports parallel build with limitations. When several flutter project is
-T option?

2021-12-21 11:03 UTC, fruska commented on README.adoc
> +the plugin execution is synchronized by default. There are some project specific build steps whivh can be run parallel, for example compile, build runner.
... `pub get`, `pub clean` and some other commands which are related directly to flutter itself can cause harm. To avoid this (?) ... ... which

2022-01-17 09:18 UTC, merged