JNG-4549 Release flutter maven plugin
BlackBeltTechnology/flutter-maven-plugin pull request #5
Opened 2023-03-10 15:10 UTC by gaborflorian

2023-03-10 15:25 UTC, noherczeg requested changes

2023-03-10 15:25 UTC, noherczeg commented on pom.xml
> +                                    <licenseName>epl_v2</licenseName>
apache

2023-03-10 15:36 UTC, gaborflorian commented on pom.xml
> +                                    <licenseName>epl_v2</licenseName>
https://github.com/BlackBeltTechnology/flutter-maven-plugin/pull/5/commits/27e92d1eaf08d8c89c2a191015a17e6f339b23b9

2023-03-10 16:54 UTC, bencegelei approved these changes

2023-03-13 07:57 UTC, robertcsakany approved these changes

2023-03-13 10:10 UTC, Madmat8 approved these changes

2023-03-13 10:33 UTC, noherczeg approved these changes

2023-03-13 13:58 UTC, merged